config/routes.rb
CoffEe::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :products do 
    resource :basket
  end

  resource :session
  get "/auth/:provider/callback", to: "sessions#create"
 

  resources :orders

  root "products#index"
  end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base

	has_many :order_products
	belongs_to :user
	

	validates :name, presence:true
	validates :email, presence: true
	validates :address_1, presence:true
	validates :postcode, presence: true
	validates :stripe_token, presence:true

	def total_price
		#local variable 
		t = 0

		self.order_products.each do |p|
			# += means add to
			t += p.price_in_pence
		end

			return t

	end


end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base

	belongs_to :order
	belongs_to :product
	
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :order_products

	validates :title, presence: true
	validates :description, presence: true
	validates :price_in_pence, presence: true

	has_attached_file :image, styles:{
		large:"960x300#",
		small: "728x90#",
		medium: "300x300#",
		thumbnail: "50x50#"
	}

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #make sure we can use basket in the view as well as the controller
  helper_method :basket

  #because the basket is everywhere on the site
  #(e.g. you want a basket on the products page or orders page)
  #we put it there.
  def basket
  	#if the user doesn't have a basket
  	#give them an empty one
  	if session[:basket].nil?
  	#basket is an empty list
  	#using set because we don't want to add the same thing twice
  	session[:basket]= Set.new
  end
  #actually give them the basket
  session[:basket]
  end

  #to use it in the views
  helper_method :current_user

  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end


end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

	def create
		#add this product to the basket
		# :product_id because we're in a nested resource
		#so not :id because we're not talking about a basket
		@product = Product.find(params[:product_id])

		#lets add this product id to the basket
		basket.add(@product.id)

		#lets tell the user
		flash[:success] = "Item added to basket"

		#go back to the product show page
		redirect_to product_path(@product)
	end

	def destroy
		#remove this product from the basket
		@product = Product.find(params[:product_id])
		basket.delete(@product.id)
		flash[:success] = "Item removed from basket"
		redirect_to product_path(@product)	
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	#a list of past orders a current user has
    if current_user.present?
      @orders = current_user.orders.all
    else
      flash[:error] = "You must be signed in"
      redirect_to root_path
    end

  end

  def show
  	#be a thanks page, this is your order
    @order = Order.find(params[:id])
  end

  def new
  	#place an order form
  	@order = Order.new
  	#add basket stuff on this order
  	#override new order with an updated one with basket stuff
  	@order = build_order(@order)

    if current_user.present?
      @order.name = current_user.name
      @order.email = current_user.email
    end
  end

  def create
  	#actually pay for an order
  	#process the payment and redirect to the show page
	@order = Order.new(order_params)
  	@order = build_order(@order)

    if current_user.present?
      @order.user = current_user
    end
    

  		if @order.save

  			Stripe::Charge.create(
  				amount: @order.total_price, 
  				currency: "gbp", 
  				card: @order.stripe_token, 
  				description: "Order number #{@order.id} - #{@order.email}")
  			
  			basket.clear
  			flash[:success] = "Thanks for ordering"
  			redirect_to order_path(@order)
  		else
  			render "new"
  		end
  end

  private
  def order_params
  		params.require(:order).permit(:name, :email, :address_1, :address_2, :city, :country, :postcode, :stripe_token)
  end

  def build_order(o)
  	#add all the session basket stuff to the order itself
  		basket.each do |basket_item|
  			#each basket_item is a product id
  			#lets find that product using the product id
  			@product = Product.find(basket_item)

  			#on this order "o", add that product
  			o.order_products.build(product_id: @product.id, quantity: 1, price_in_pence: @product.price_in_pence)
  		end
  		#send back this order
  		return o
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	#list out all the live ProductsController
  	@products = Product.where(is_live: true)
  end

  def show
  	#show an individual one
  	@product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
	#make a new user if the user doesn't exist
	#save them to a session [:user_id]
	@provider = auth_hash[:provider]
	@provider_id = auth_hash[:uid]

	@users = User.where(provider:@provider, provider_id: @provider_id)

	if @users.size == 0
		#create a new user
		@user = User.new
		@user.provider = @provider
		@user.provider_id = @provider_id
		@user.name = auth_hash[:info][:name]
		@user.email = auth_hash[:info][:email]
		@user.image = auth_hash[:info][:image]
		@user.save

		session[:user_id] = @user.id

	else
		#sign in as that first user
		@user = @users.first
		session[:user_id] = @user.id
	end
	flash[:success] = "logged in"
	redirect_to root_path

end

def destroy
	#log out
	session[:user_id] = nil
	flash[:success] = "Logged out"
	redirect_to root_path
end

protected
def auth_hash
	request.env['omniauth.auth']
end




end

app/helpers/application_helper.rb
module ApplicationHelper

	def quid(num)
		number_to_currency num / 100.0, unit: "&pound;"
	end

end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffEe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_e0e0pwUuanDlnHRlQqZ1XPJT');
  // ...
</script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<h1><%= link_to "Coff.ee", root_path %></h1>
		<nav>
			<%#instead of linking up a little bit of text, link up the whole section between do and end %>
			<%= link_to new_order_path do %>
			<strong><%= pluralize basket.size, "item" %> in your basket</strong>
			<% end %>

				<% if current_user.present? %>
				<%= image_tag current_user.image %>
				<%= current_user.name %>

				<%= link_to "Orders", orders_path %>
				<%= link_to "Log out", session_path, method: :delete %>
				<% else %>	

				<a href "/auth/facebook">Sign in with Facebook</a>
				<a href = "/auth/twitter">Sign in with Twitter</a>
				<% end %>	
		</nav>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h2> Your Orders </h2>

<% @orders.each do |o| %>

	<div class="order">
		<%= link_to order_path(o) do %>
			Order <%= o.id %> - <%= quid o.total_price %>
		<% end %>
	</div>
<% end %>		

app/views/orders/new.html.erb
<h2>You're one step away from order lovely coffee</h2>

<table>
<thead>
	<tr>
		<th>Product</th>
		<th>Qty</th>
		<th>Price</th>
		<th></th>
	</tr>
<t/head>

<tbody>
	<% @order.order_products.each do |p| %>
		<tr>
			<td><%= p.product.title %></td>
			<td><%= p.quantity %></td>
			<td><%= quid p.price_in_pence %></td>
			<td>Remove</td>
    </tr>
	<% end %>
    <tr>
      <td colspan="2">Total Price</td>
        <td><strong><%= quid @order.total_price %></strong></td>
        <td></td>
      </tr>
</tbody>

</table>

<%= simple_form_for @order do |f| %>
<%= f.input :name %>
<%= f.input :email %>
<%= f.input :address_1 %>
<%= f.input :address_2 %>
<%= f.input :city %>
<%= f.input :postcode %>
<%= f.input :country, as: :string %>

<form action="" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>
  
<%= f.button :submit %>

<% end %>

app/views/orders/show.html.erb
<h2> Order no <%= @order.id %></h2>

<% @order.order_products.each do |p| %>
	<p><%= p.product.title %></p>
<% end %>

	

app/views/products/index.html.erb
<h2>Welcome to our Coff.ee</h2>

<p>Here you will find the finest coffees in the world</p>

<% @products.each do |p| %>
<div class="product">
	<%= image_tag p.image(:medium) %>
	<h3><%= link_to p.title, product_path(p) %></h3>
	<p><%= p.price_in_pence %></p>
	<p><%= link_to "Read more...", product_path(p) %></p>
	<% if basket.include?(p.id) %>
		<%= link_to "Remove from Basket", product_basket_path(p), method: :delete %>
	<% else %>
		<%= link_to "Add to Basket", product_basket_path(p), method: :post %>
	<% end %>
</div>
	<% end %>

app/views/products/show.html.erb
<article>
	<%= image_tag @product.image(:large) %>

	<h2><%= @product.title %></h2>

	<%= simple_format @product.description %>

	<p>£<%= @product.price_in_pence %></p>

	<p>Added <%= time_ago_in_words @product.created_at %> ago</p>

	<% if basket.include?(@product.id) %>

		<%= link_to "Remove from Basket", product_basket_path(@product), method: :delete %>

	<% else %>

		<%= link_to "Add to Basket", product_basket_path(@product), method: :post %>

	<% end %>



	
	
</article>